apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: posts
  labels:
    strimzi.io/cluster: doc-kafka-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824